### ISSUE TITLE
Ecran blanc

### ISSUE THREAD

**Issue by Copainduweb** [xurei/twitch-highlights-logger#1]
- Operating system: Windows 10
- App version: 0.0.6

Le logiciel démarre parfois sur un écran blanc fixe. Il faut le redémarrer en boucle jusquà ce qu'il remarche.

**Comment by xurei** [comment]
This is partially solved. I leave this open until I find the actual cause of this bug.
For the moment, it just detects the problem and reloads the page.
This is dirty, but it is efficient.

**Comment by avanjool** [comment]
Windows 10 and version 0.0.8 - getting a grey screen. I do see the window does that reload because it blinks orange in my taskbar periodically but it never changes from a blank screen. I've attempted to restart the program many times but have never seen anything other than a blank grey screen.
![TwitchHighlights_2021-06-15_13-32-46](https://user-images.githubusercontent.com/31154248/122119743-66704680-cdde-11eb-9511-a7a7de0a7583.png)

**Comment by xurei** [comment]
@avanjool I'm currently fixing this issue. A new version will be available very soon

**Comment by avanjool** [comment]
Awesome, I look forward to it! Until then it's working great in Ubuntu

**Comment by xurei** [comment]
The bug is finally fixed ! The new release should work without any problem.
https://github.com/xurei/twitch-highlights-logger/releases/tag/v0.0.9
